name: Create Release & Publish to NPM
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: WhatsApp Widget ${{ github.ref }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          registry-url: https://registry.npmjs.org/

      - name: Checkout tag
        run: |
          git fetch --all --tags --prune -f
          git checkout $(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Run publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
